### ISSUE TITLE
when using react18 ，there is a bug in ‘resetsize’

### ISSUE THREAD

**Issue by qirong77** [uiwjs/react-markdown-editor#177]
when i using react18 and  using this as a component
const Editorx = ({ file }) => {
 <MarkdownEditor value={file.content} onChange={(editor, data, value) => setContent(value)}></MarkdownEditor>
}
than it give me a error
 Uncaught TypeError: Cannot read properties of undefined (reading 'setSize')
it really spend me a lot of time to save this problem.and when i useing react under 18 .it works!

**Comment by jaywcjlove** [comment]
@qirong77 The bug has been fixed. Upgrade `v4.0.3`

Example: https://codesandbox.io/embed/uiwjs-react-markdown-editor-issues-177-hscjnx?fontsize=14&hidenavigation=1&theme=dark
