### ISSUE TITLE
How to remove toolbar at all

### ISSUE THREAD

**Issue by lofti198** [uiwjs/react-markdown-editor#188]
Thank you for this awesome component! Please tell, how to remove toolbar at all?
![image](https://user-images.githubusercontent.com/42960488/187067452-6723a497-29fb-4133-ae92-0cd95bb60170.png)

I tried passing empty array, however right icons (switch to fullscreen and preview) still remain.
` <MarkdownEditor
            value={markdown}
            onChange={(value, viewUpdate) => setMarkdown(value)}
            toolbars={[]}
          />`

**Comment by lofti198** [comment]
I found workaroung with: display none, however maybe there is some parameter for that?
`.md-editor-toolbar {
  display: none;
}
`

**Comment by jaywcjlove** [comment]
@lofti198 Upgrade [v5.2.0](https://github.com/uiwjs/react-markdown-editor/releases/tag/v5.2.0)

**Comment by lofti198** [comment]
> @lofti198 Upgrade [v5.2.0](https://github.com/uiwjs/react-markdown-editor/releases/tag/v5.2.0)

Cool! But for now its still not available from npm, or I miss smth?

**Comment by lofti198** [comment]
Thank you for fast help! It works awesome!
