### ISSUE TITLE
How to make editor focused (active with cursor in it) on component load

### ISSUE THREAD

**Issue by lofti198** [uiwjs/react-markdown-editor#189]
How to make editor focused (active with cursor in it) on component load? I guess I should do that with useEffect, however nor using refs, neigher getting element from document did not work for me:
![image](https://user-images.githubusercontent.com/42960488/187069194-3b92d8ee-7eb7-4b29-9998-03ea84c83c79.png)

**Comment by jaywcjlove** [comment]
@lofti198  Please provide me with an example via [codesandbox.io](https://codesandbox.io/embed/react-markdown-editor-ybpce?file=/src/App.js).

**Comment by lofti198** [comment]
Hi! Ready https://codesandbox.io/s/compassionate-hypatia-kgf4xc?file=/src/components/JSMindMM.js , however getting strange error:
![image](https://user-images.githubusercontent.com/42960488/187073884-b89738e4-7a7b-43c9-b9a4-fbb7697c9e14.png)

It worked OK on my local machine

**Comment by jaywcjlove** [comment]
This way I can't help you. @lofti198

**Comment by lofti198** [comment]
Today I fixed issue with codesandbox and now you can see the working component here: https://codesandbox.io/p/github/lofti198/react-jsmind/draft/nostalgic-wright?file=%2Fsrc%2Fcomponents%2FJSMindMM.js . Any ideas now how to make editor get focus automatically on component mount?

**Comment by jaywcjlove** [comment]
@lofti198 Here is an incomplete example. https://codesandbox.io/embed/react-markdown-editor-uiwjs-react-markdown-editor-issues-189-4imdj6?fontsize=14&hidenavigation=1&theme=dark

**Comment by jaywcjlove** [comment]
```jsx
import MarkdownEditor from "@uiw/react-markdown-editor";
import { useState, useRef, useEffect } from "react";
const code = `# title\n\nHello World!\n\n`;

export function Editor() {
  const $ref = useRef(null);
  const [markdownVal, setMarkdownVal] = useState(code);

  useEffect(() => {
    setTimeout(() => {
      const view = $ref.current?.editor.current?.view;
      if (view) {
        view.focus();
        view.dispatch(view.state.update({ selection: { anchor: 12 } }));
      }
    }, 200);
  }, [$ref]);
  return (
    <MarkdownEditor
      ref={$ref}
      value={markdownVal}
      onChange={(value, vu) => {
        setMarkdownVal(value);
      }}
      onStatistics={(data) => {
        // main = data.selectionAsSingle;
        // console.log("data:", data.selectionAsSingle);
      }}
    />
  );
}
```

**Comment by lofti198** [comment]
Hi! Thank you very much for this work! I checked your solution in your codesandbox and it works completely cool! At the same time, when integrated in my code I somewhy get editor as null and the subsequent condition (if(view)...) doesn't do its job to set focus: https://codesandbox.io/p/github/lofti198/react-jsmind/draft/nostalgic-wright?file=%2Fsrc%2Fcomponents%2FJSMindMM.js

![image](https://user-images.githubusercontent.com/42960488/187585862-81ee8e37-b43f-4d42-8cde-351a1db0962e.png)

Maybe you see what I missed?

**Comment by lofti198** [comment]
Finally we found that it works, but for version 5.3.0.
