### ISSUE TITLE
How to avoid increasing width and just have auto line wrapping?

### ISSUE THREAD

**Issue by lofti198** [uiwjs/react-markdown-editor#190]
Having the following issue: when number of characters in line is more, than its width - the whole editor is being increased. Any ideas how to make just auto line wrapping? Video demo: https://somup.com/c3jviXUlmF . Component is styled like this. Version 5.2.0

`<MarkdownEditor
                style={{
                  height: "150px",
                  overflow: "scroll",
                  padding: "8px",
                }}
                value={markdown}
                onChange={(value, viewUpdate) => {
                  setMarkdown(value);
                }}
              />`

**Comment by jaywcjlove** [comment]
https://codesandbox.io/embed/react-markdown-editor-uiwjs-react-markdown-editor-issues-190-kpfm3e?fontsize=14&hidenavigation=1&theme=dark

I have no way to reproduce the problem.
@lofti198

**Comment by lofti198** [comment]
> https://codesandbox.io/embed/react-markdown-editor-uiwjs-react-markdown-editor-issues-190-kpfm3e?fontsize=14&hidenavigation=1&theme=dark
> 
> I have no way to reproduce the problem. @lofti198

I see, tested it and it really works almost without changing control width. At the same time - is there a way to make autowrap (auto new line, when amount of text is longer than one line width)? Like this:
![image](https://user-images.githubusercontent.com/42960488/187413328-ebc2ac03-406e-40b5-971d-6eac135dce8d.png)

In your case its by default like this:
![image](https://user-images.githubusercontent.com/42960488/187413417-4385bdf5-61bf-4af6-b25a-9275483942ce.png)

**Comment by jaywcjlove** [comment]
@lofti198 This might be the effect you want.

```diff
+ import { EditorView } from "@codemirror/view";

<MarkdownEditor
  value={markdownVal}
+  extensions={[EditorView.lineWrapping]}
  onChange={(value) => {
    setMarkdownVal(value);
  }}
/>
```

![image](https://user-images.githubusercontent.com/1680273/187423451-a7892f32-90f9-43cf-bd52-03bec9ca6504.png)

**Comment by lofti198** [comment]
Cool! It works completely how I need! Can I somehow donate for your fast and accurate help?

**Comment by jaywcjlove** [comment]
GitHub does not support donations in China.  You can star repositories.

@lofti198

**Comment by lofti198** [comment]
Maybe I can [buy you a coffee](https://www.buymeacoffee.com/)? Also I would appreciate if you check [this issue](https://github.com/uiwjs/react-markdown-editor/issues/189#issuecomment-1230693792) with getting focus (a fixed codesandbox so you could see how it works for me)

**Comment by jaywcjlove** [comment]
@lofti198 oh, slow down, I've dealt with 4 issues.
