### ISSUE TITLE
How to spread preview on the whole width (not the half of editor)

### ISSUE THREAD

**Issue by lofti198** [uiwjs/react-markdown-editor#192]
How to spread preview on the whole width (not the half of editor) by default? 
![image](https://user-images.githubusercontent.com/42960488/188325971-4fcc11a7-5769-4bf1-90c2-20cabdbcc791.png)

Thank you in advance!

**Comment by jaywcjlove** [comment]
@lofti198 Upgrade `v5.7.0`

```diff
import MarkdownEditor from '@uiw/react-markdown-editor';

const Dome = () => (
  <MarkdownEditor
+    previewWidth="100%"
  />
);
```

**Comment by lofti198** [comment]
Cool! Works awesome
