### ISSUE TITLE
Default code toolbar

### ISSUE THREAD

**Issue by AustinKelsay** [uiwjs/react-markdown-editor#193]
Is there any kind of default code toolbar or does it have to be made custom?

If not are their any references I can go off of?

**Comment by jaywcjlove** [comment]
@AustinKelsay Like this?

<img width="727" alt="image" src="https://user-images.githubusercontent.com/1680273/191637328-8348bb33-eb61-4ace-b6b0-ec80fca83ccc.png">

**Comment by AustinKelsay** [comment]
> @AustinKelsay Like this?
> 
> <img alt="image" width="727" src="https://user-images.githubusercontent.com/1680273/191637328-8348bb33-eb61-4ace-b6b0-ec80fca83ccc.png">

Yes exactly

**Comment by jaywcjlove** [comment]
@AustinKelsay Upgrade `v5.8.0`

**Comment by AustinKelsay** [comment]
Great, thank you!
