### ISSUE TITLE
v5.11.2 breaks CSS imports

### ISSUE THREAD

**Issue by nfts2me** [uiwjs/react-markdown-editor#204]
After updating to [v5.11.2](https://github.com/uiwjs/react-markdown-editor/releases/tag/v5.11.2) CSS imports are broken:
`Module not found: Can't resolve '@uiw/react-markdown-editor/markdown-editor.css'`

On v5.11.1 we have no issues.

The imports we have on our code are like this:
```
import '@uiw/react-markdown-editor/markdown-editor.css';
import '@uiw/react-markdown-preview/markdown.css';
```

**Comment by jaywcjlove** [comment]
@nfts2me Upgrade `v5.11.3`
