### ISSUE TITLE
Markdown Preview hide not works

### ISSUE THREAD

**Issue by 92sajid110** [uiwjs/react-markdown-editor#205]
I want to hide Preview but not works.
toolbarsMode={["fullscreen"]}

But it shows approx 10px of preview on right and preview button is hidden
previewProps={{
style:{display:none}
        }} 
        same result not hiding completely

**Comment by jaywcjlove** [comment]
@92sajid110 Upgrade `v5.12.0`

```diff
import React from "react";
import MarkdownEditor from '@uiw/react-markdown-editor';

const Dome = () => (
  <MarkdownEditor
    value="Hello Markdown!"
    height="200px"
+    enablePreview={false}
  />
);
```

**Comment by jaywcjlove** [comment]
https://codesandbox.io/embed/react-markdown-editor-https-github-com-uiwjs-react-markdown-editor-issues-205-c3kqhd?fontsize=14&hidenavigation=1&theme=dark

**Comment by 92sajid110** [comment]
> ```diff
> +    enablePreview={false}
> ```

Thanks a lot.
It works.
