### ISSUE TITLE
Wrap text in editor

### ISSUE THREAD

**Issue by 92sajid110** [uiwjs/react-markdown-editor#206]
Hello,
I want to wrap text to new line just like vs code.
I have given the fixed height to the editor but didn't find wrapText option

Thanks

**Comment by jaywcjlove** [comment]
I do not understand what you mean. @92sajid110

**Comment by 92sajid110** [comment]
in vs code it is Word wrap
Word wrap is a feature in VS Code that automatically adjusts the display of long lines of code or text so that they fit within the editor's visible area. When word wrap is enabled, long lines are wrapped onto the next line, making it easier to read and edit code or text without having to scroll horizontally.

**Comment by jaywcjlove** [comment]
@92sajid110 https://codesandbox.io/embed/react-markdown-editor-https-github-com-uiwjs-react-markdown-editor-issues-206-v2pyr6?fontsize=14&hidenavigation=1&theme=dark

```diff
import MarkdownEditor from "@uiw/react-markdown-editor";
import { useState } from "react";
+ import { EditorView } from "@codemirror/view";

const code = `# title\n\nHello World!\n\n`;

export default function App() {
  const [markdownVal, setMarkdownVal] = useState(code);
  return (
    <div className="App">
      <MarkdownEditor
+        extensions={[EditorView.lineWrapping]}
        value={markdownVal}
        onChange={(value) => {
          setMarkdownVal(value);
        }}
      />
    </div>
  );
}
```

**Comment by 92sajid110** [comment]
Thanks

**Comment by 92sajid110** [comment]
Is there any option to highlight custom text like
<div></div> i made custom component for react <Div {...}>{...}</Div>
i want to highlight as this is tag
