### ISSUE TITLE
Asynchronous value set, preview value not updated

### ISSUE THREAD

**Issue by Junfeizhao** [uiwjs/react-markdown-editor#210]
look this:
![65a299c40ead867704d21c6fa726056d](https://github.com/uiwjs/react-markdown-editor/assets/47941990/041f4341-7366-415f-8f63-f93753e714bf)
![cd6d85cd4cf727fd2214c72708e1c500](https://github.com/uiwjs/react-markdown-editor/assets/47941990/b23d89db-8085-4eb6-8442-d0a63f692e79)

The value previewed on the right is old. How to solve this problem

**Comment by jaywcjlove** [comment]
@Junfeizhao Upgrade `v5.13.1`

**Comment by Junfeizhao** [comment]
thanks
