### ISSUE TITLE
Switch to fullscreen 

### ISSUE THREAD

**Issue by mauro-rogledi** [uiwjs/react-markdown-editor#217]
Is there a way to know when the user switches from normal to full screen mode?
Thanks

**Comment by jaywcjlove** [comment]
@mauro-rogledi 

There are two methods to implement:

1. Listening to the className of the body DOM node can determine if it is fullscreen.
2. Customizing Toolbars and adding click events again.

```jsx
import MarkdownEditor, { preview, fullscreen } from '@uiw/react-markdown-editor';

const customFullscreen: ICommand = {
  ...fullscreen,
  button: (command, props, opts) => (
    <FullscreenButton
      onClick={(evn, isFull) => {}}
      command={command}
      editorProps={{ ...props, ...opts }}
    />
  ),
};

<MarkdownEditor
  value="Hello Markdown!"
  height="200px"
  toolbarsMode={[
    preview, customFullscreen
  ]}
/>
```

@mauro-rogledi This is a possible way to achieve your requirements.

**Comment by mauro-rogledi** [comment]
Thanks, but there are some problems:

-` import MarkdownEditor, { preview, fullscreen } from '@uiw/react-markdown-editor';`
fullscreen and preview are not exported then I have error
- ` <FullscreenButton`
same problem

**Comment by abhinavgautam-07** [comment]
@mauro-rogledi can you share a working example
