### ISSUE TITLE
How is preview show by default

### ISSUE THREAD

**Issue by a1392136** [uiwjs/react-markdown-editor#222]
1. When I import the editor as follows, the preview is not show, How to control preview from ts code
2. Is it possible to only enable preview mode without editing, Instead of using  <MarkdownEditor.Markdown />
```
const [markdown, setMarkdown] = useState("");
<MarkdownEditor
            height="300px"
            value={markdown}
            onChange={(value) => {
              setMarkdown(value);
            }}
          />
```

**Comment by jaywcjlove** [comment]
@a1392136 You can provide a reproducible example of the error, and I'll take a look.

**Comment by a1392136** [comment]
> @a1392136 You can provide a reproducible example of the error, and I'll take a look.您可以提供一个可重现的错误示例，我会看一下。
I use this component in my electron application. 
The markdown editor works fine, but previews are not shown by default. 

**default:**
![image](https://github.com/uiwjs/react-markdown-editor/assets/13248153/28be447b-ec5a-459a-8f0c-c7c8a22f3df4)

**The desired effect:**
![image](https://github.com/uiwjs/react-markdown-editor/assets/13248153/5ecaa5d3-44a0-4243-aad3-2335aa13514d)

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-markdown-editor/blob/460df663c8d089effb1a61acd6e904b00b43ec5b/core/src/index.tsx#L29-L30

```diff
<MarkdownEditor
  value={markdownVal}
+  visible={true}
```
