### ISSUE TITLE
React v19 Not Supported

### ISSUE THREAD

**Issue by vientorepublic** [uiwjs/react-markdown-editor#237]
It's time to update to React v19 (#236)

```
npm error   react@"^19.0.0" from the root project
npm error   peer react@">=16.3" from @fortawesome/react-fontawesome@0.2.2
npm error   node_modules/@fortawesome/react-fontawesome
npm error     @fortawesome/react-fontawesome@"^0.2.2" from the root project
npm error   14 more (@uiw/react-codemirror, @uiw/react-markdown-editor, ...)
```

**Comment by jaywcjlove** [comment]
> npm error   react@"^19.0.0" from the root project
> npm error   peer react@">=16.3" from @fortawesome/react-fontawesome@0.2.2
> npm error   node_modules/@fortawesome/react-fontawesome
> npm error     @fortawesome/react-fontawesome@"^0.2.2" from the root project
> npm error   14 more (@uiw/react-codemirror, @uiw/react-markdown-editor, ...)

This error message indicates that one of your project's dependencies requires `react` version `^19.0.0`, but another dependency, `@fortawesome/react-fontawesome@0.2.2`, requires `react` version `>=16.3`. These version requirements are incompatible, causing a conflict.

@vientorepublic

**Comment by vientorepublic** [comment]
![Screenshot 2024-12-14 at 4 29 29 PM](https://github.com/user-attachments/assets/2b3ca9d9-b594-4919-80a3-cbff0c3d98ea)

I confirmed that there were no issues with peer dependency in the newly created project. thank you
