### ISSUE TITLE
Unsafe Component Lifecycles 

### ISSUE THREAD

**Issue by cbschuld** [uiwjs/react-markdown-editor#32]
Hi Kenny,

Thank you for the great work on this.  Starting to use it in a project.  Curious if you are tinkering with removing the unsafe lifecycles calls _(componentWillMount, componentDidMount, componentDidUpdate)_? I am happy to take that on if you have not already started the work?

Thanks//cbs

**Comment by jaywcjlove** [comment]
@cbschuld I haven't started yet. I would love to see your PR. Thx!

**Comment by jaywcjlove** [comment]
Upgrade `+ @uiw/react-markdown-editor@2.0.2`
