### ISSUE TITLE
自定义onChange函数 输入字符后光标自动调回

### ISSUE THREAD

**Issue by Uncharted30** [uiwjs/react-markdown-editor#35]
你好 请问这个问题如何解决？

**Comment by jaywcjlove** [comment]
@Uncharted30 ”输入字符后光标自动调回“，这个没有明白什么意思

**Comment by Uncharted30** [comment]
不好意思 打到一半回去看了一眼 回来就忘了标题没打完。。
就是在editor中任意位置输入字符，光标都会跳回到第一行的起始位置

**Comment by jaywcjlove** [comment]
@Uncharted30 你这个 value 受控了吧。

**Comment by Uncharted30** [comment]
不好意思...我没太明白你的意思，我现在用的代码是直接复制的说明里的例子，也就是controlled usage这个例子，麻烦您稍微解释一下可以吗？

**Comment by Uncharted30** [comment]
问题解决了。。感谢回复。。

**Comment by Ryan-lixuan** [comment]
你好，我也遇到这个问题，请问该怎么解决啊

**Comment by jaywcjlove** [comment]
@Ryan-lixuan 控制内容尽量使用 `codemirror` 内部方法。

https://github.com/uiwjs/react-markdown-editor/issues/41#issuecomment-719137297
