### ISSUE TITLE
Global CSS import within the package is causing an issue with Next.js

### ISSUE THREAD

**Issue by imbhargav5** [uiwjs/react-markdown-editor#42]
When using this component with Next.js, I am facing this error. Specifically at lines like these.
https://github.com/uiwjs/react-markdown-editor/blob/2fd2077ec910cd2a21a99b3b5085d30266392eff/src/components/CodeMirror/index.tsx#L6
https://github.com/uiwjs/react-markdown-editor/blob/2fd2077ec910cd2a21a99b3b5085d30266392eff/src/components/CodeMirror/index.tsx#L7

error - ./node_modules/@uiw/react-markdown-editor/lib/esm/components/CodeMirror/codemirror.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm

**Perhaps we can expose an export that is unstyled and one that is styled?**

1. Expose UnstyledComponents
```jsx
...
export default UnstyledComponent
``` 
2. Expose a module which has styles also imported.
```jsx
import UnstyledComponent from ...
import styles from ...

export default ...

```

**Comment by stLoiz** [comment]
@imbhargav5  Have you solved this?

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/issues/52

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/issues/52#issuecomment-848969341
@stLoiz @imbhargav5

**Comment by LKHcoding** [comment]
> [uiwjs/react-md-editor#52](https://github.com/uiwjs/react-md-editor/issues/52) quote
@jaywcjlove 

i can't solved this problem with `next-remove-imports`

error :
```
Server Error
ReferenceError: navigator is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
...../node_modules/codemirror/lib/codemirror.js (18:19)
```

plz help me what should i do 😥

**Comment by jaywcjlove** [comment]
https://codesandbox.io/s/nextjs-example-react-codemirror-bimq7?file=/pages/index.js

@imbhargav5 


```js
import { useEffect, useState } from "react";

function HomePage() {
  const [comp, setComp] = useState();
  useEffect(() => {
    if (window) {
      import("@uiw/react-codemirror").then((obj) => {
        if (!comp) {
          setComp(obj.default);
        }
      });
    }
  }, []);

  const Comps = comp;
  return (
    <div>
      {Comps && (
        <Comps
          value="const a = 0;"
          options={{
            mode: "jsx"
          }}
        />
      )}
    </div>
  );
}

export default HomePage;

```

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/issues/52#issuecomment-848969341

**Comment by jaywcjlove** [comment]
- https://github.com/uiwjs/react-md-editor/issues/446#issue-1417594634

Example: https://codesandbox.io/s/nextjs-example-react-md-editor-qjhn7?file=/pages/index.js  
Example: [@uiwjs/next-remove-imports/example](https://github.com/uiwjs/next-remove-imports/tree/main/example)  
Example: https://next-remove-imports-example.vercel.app
