### ISSUE TITLE
Why onBlur removed all text in editor ?

### ISSUE THREAD

**Issue by SuroHak** [uiwjs/react-markdown-editor#68]
1. write text.
2. onBlur from the editor.
3. do some other action in the page

**Comment by jaywcjlove** [comment]
@SuroHak There is no way to judge your problem without demonstration.

**Comment by SuroHak** [comment]
@jaywcjlove you can see an example here.
https://codesandbox.io/s/wizardly-worker-43hwb?file=/src/App.js

1. input in the markdown
2. input in the other input element

**Comment by jaywcjlove** [comment]
https://codesandbox.io/s/elastic-breeze-9k7st?file=/src/App.js

@SuroHak Upgrade `+ @uiw/react-markdown-editor@3.1.1`

```jsx
import MarkdownEditor from "@uiw/react-markdown-editor";
import { useState } from "react";
import "./styles.css";

export default function App() {
  const [val, setVal] = useState("");

  return (
    <div className="App">
      <input
        value={val}
        onChange={(e) => {
          setVal(e.target.value);
        }}
      />
      <MarkdownEditor
        value={val}
        onChange={(editor, data, value) => {
          setVal(value);
        }}
      />
    </div>
  );
}

```

**Comment by SuroHak** [comment]
ok I will try

**Comment by SuroHak** [comment]
Seems fixed )) Thank you @jaywcjlove
